Adding some error protection on download

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -22,7 +22,11 @@ cd $1
 while read url; do
   if [ -n "$url" ]; then
     echo Vendoring $url | indent
-    curl -L --silent $url > $1/bin/terraform.zip
+    curl -L "$url" -o $1/bin/terraform.zip
+    if [ $? -ne 0 ]; then
+        >&2 echo "Couldn't download $url" 
+        exit 1
+    fi
     cd $1/bin && $UNZIP_COMMAND terraform.zip && rm terraform.zip
   fi
 done < .terraform_url
